name: mp_class_xlo_shop
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4

  flutter_signin_button: ^2.0.0

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  pin_code_fields: ^7.3.0
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3

flutter_native_splash:
  color: '#ffffff'
  image: assets/images/splash_image.png
  android: true
  android_gravity: fill
  ios: true
  ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Caslon224
      fonts:
        - asset: assets/fonts/Caslon224-regular.TTF
        - asset: assets/fonts/Caslon224-regular-italic.TTF
          style: italic
        - asset: assets/fonts/Caslon224-bold.TTF
          weight: 700
        - asset: assets/fonts/Caslon224-bold-italic.TTF
          style: italic
          weight: 700
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
